Get rid of prepared dependency tarball of 3rd-party packages

diff --git a/build/bin/build-srpm b/build/bin/build-srpm
--- a/build/bin/build-srpm
+++ b/build/bin/build-srpm
@@ -75,21 +75,21 @@ build_generic_tarball() {
 build_ssm_client_tarball() {
     local name=$1
     local version=$2
-    local sub_packages=(mongodb_exporter mysqld_exporter postgres_exporter proxysql_exporter qan-agent node_exporter ssm-client pid-watchdog)
+    local sub_packages=(mongodb_exporter mysqld_exporter postgres_exporter proxysql_exporter pid-watchdog qan-agent node_exporter ssm-client)
     local subdir=${tmp_dir}/rpmbuild/SOURCES/${name}
 
     mkdir -p $subdir
-    for sub_packages in ${sub_packages[@]}; do
-        pushd ${submodule_dir}/$sub_packages
+    for sub_package in ${sub_packages[@]}; do
+        pushd ${submodule_dir}/$sub_package
             local tag=$(git tag -l --sort=-version:refname "v*" --merged | head -n 1)
-            if [ -f "${subdir}/${sub_packages}-${tag}.tar.gz" ]; then
-                echo "${sub_packages}-${tag}.tar.gz exists, skipped"
+            if [ -f "${subdir}/${sub_package}-${tag}.tar.gz" ]; then
+                echo "${sub_package}-${tag}.tar.gz exists, skipped"
             else
                 git checkout $tag
 
-                pull_dep_in_place $sub_packages
+                pull_dep_in_place $sub_package
 
-                tar czf ${subdir}/${sub_packages}-${tag}.tar.gz ../${sub_packages}
+                tar czf ${subdir}/${sub_package}-${tag}.tar.gz ../${sub_package}
             fi
         popd
     done
@@ -100,20 +100,52 @@ build_ssm_client_tarball() {
     popd
 }
 
+build_3rd_tallbar() {
+    local package=$1
+    local dep_src=$2
+    local dep_dest=$3
+    local ignore_error=$4
+
+    pushd ${tmp_dir}/rpmbuild/SOURCES
+        local tarball=$(find . -maxdepth 1 -type f -iname "${package}*.tar.gz" | head -1)
+        if [ -n "${tarball}" ]; then
+            tar -zxf ${tarball}
+            local package_dir=$(find . -maxdepth 1 -type d -iname "${package}*" | head -1)
+            if [ -n "${dep_src}" ]; then
+                cp ${dep_src} ${package_dir}/${dep_dest}
+            fi
+            pushd ${package_dir}
+                pull_dep_in_place $package $ignore_error
+            popd
+            rm -f ${tarball}
+            tar -czf ${tarball} ${package_dir}
+        fi
+    popd
+}
+
 pull_dep_in_place() {
     local package=$1
+    local ignore_error=$2
 
-    if [[ -f Gopkg.toml ]]; then
+    if [[ -f yarn.lock ]]; then
+        export NG_CLI_ANALYTICS=ci # disable sharing anonymous usage data with angular
+        if [ -n "${ignore_error}" ]; then
+            yarn || true
+        else
+            yarn
+        fi
+    elif [[ -f Gopkg.toml ]]; then
         export GOPATH=${tmp_dir}/go
+        rm -rf ${tmp_dir}/go/pkg/dep/sources
         package_path=${tmp_dir}/go/src/$(git_url_to_import_path $(git remote get-url origin))
         mkdir -p $(dirname ${package_path})
         cp -rfT ${submodule_dir}/$package ${package_path}
         pushd ${package_path}
-            dep ensure
+            GO111MODULE=off dep ensure
         popd
         cp -r ${package_path}/vendor ./
     elif [[ -f go.mod ]]; then
-        go mod vendor
+        GO111MODULE=on go mod vendor
     elif [[ -f package.json ]]; then
         export NG_CLI_ANALYTICS=ci # disable sharing anonymous usage data with angular
         npm install
@@ -125,6 +157,7 @@ create_srpm() {
     local version=
 
     rm -rf ${tmp_dir}/rpmbuild/SRPMS/${package}*
+    rm -rf ${tmp_dir}/rpmbuild/SOURCES/*
     mkdir -vp ${tmp_dir}/rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
 
     pushd ${submodule_dir}/$package
@@ -154,6 +187,13 @@ create_srpm() {
             build_generic_tarball $package $version "password-page"
         else
             build_generic_tarball $package $version
+        fi
+    else
+        if [ "$package" == "grafana" ]; then
+            build_3rd_tallbar $package "grafana-yarn.lock" "yarn.lock" "1"
+            build_3rd_tallbar "node-sass" "node-sass-package-lock.json" "package-lock.json"
+        else
+            build_3rd_tallbar $package
         fi
     fi
 
@@ -188,6 +228,11 @@ check_commands() {
 
     if ! command -v npm &> /dev/null; then
         echo "'npm' is required to run this script"
+        exit 1
+    fi
+
+    if ! command -v yarn &> /dev/null; then
+        echo "'yarn' is required to run this script"
         exit 1
     fi
 }
